name: "Auto Release"

# Only a single job with this concurrency can run at any given time
concurrency: release

on:
  # https://crontab.guru/#6_17_*_*_2
  # Every Tuesday at 5:06pm UTC & 9:06am US West Coast.
  # GitHub Actions defaults to UTC:
  # There is high load on GitHub Actions at the top of the hour:
  #
  #     Note: The schedule event can be delayed during periods of high loads of
  #     GitHub Actions workflow runs. High load times include the start of every
  #     hour. To decrease the chance of delay, schedule your workflow to run at a
  #     different time of the hour.
  # schedule:
  #   - cron: "6 17 * * 2"

  push:
    branches:
      - release
    tags:
      - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --rm-dist --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          BUCKET_ID: dl-1309519128
          BUCKET_REGION: us-ap-hongkong-1
