name: Generate documents for website

on:
  push:
    tags:
      - "v*" # generate new docs when release

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Generate docs
      run: go run docs/gen.go website-docs

    - name: Commit files
      run: |
        git config --local user.email "heigliner-robot@h8r.io"
        git config --local user.name "heigliner-robot"
        git add .
        git commit -m "Update docs" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: website-docs