name: echo

on:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches: 
    - main
    - dev

jobs:

  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Echo
      run: echo "github action"
