name: Unit-Test

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: 
    - main
    - dev

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test
